### ISSUE TITLE
IE11 - Examples not working

### ISSUE THREAD

**Issue by grovolis** [visjs/vis-network#68] opened 2019-08-13 16:28 UTC
Hi all, 

Just wanted to ask if the latest version of vis-network supports IE11? I couldn't find any coverage page on the website. If so, the last two versions I've tried seem to be broken for IE 11 (e.g [basic usage](https://visjs.github.io/vis-network/examples/network/basicUsage.html) example gets a console error `SCRIPT5007: Object expected
vis-network.min.js (25,36467)`

It has to do with the object.extend() method. 

Sorry if IE11 is not supported, I didn't know and please feel free to close this issue.

**Comment by mojoaxel** [comment] 2019-08-13 16:55
duplicate of #57

**Closed** 2019-08-13 17:05 UTC
Labels: bug, duplicate
