### ISSUE TITLE
Edge arrows appear above node labels

### ISSUE THREAD

**Issue by bglasgo** [visjs/vis-network#883] opened 2020-07-22 14:39 UTC
On my network, arrows on both and and middles of edges appear drawn a layer above any node label text, while the edges themselves are underneath the node label.

**Comment by Thomaash** [comment] 2020-07-30 19:48
Hmm, this was introduced in #761. The reason is that the arrows can pierce into nodes and therefore have to be above the nodes. The problem is that a node and its label is a single unit even when the label is outside of the node, so there's no simple way to fix this.

**Comment by bglasgo** [comment] 2020-08-04 04:02
Hmm, im not sure what you mean, all my arrows end up outside the nodes border so that wouldnt be an issue.  I haven't looked around in the code but, perhaps offer the user a setting of whether these get drawn above or below everything?

**Comment by Thomaash** [comment] 2020-08-08 18:54
Hi @bglasgo,

for all shapes except for custom this should be resolved with the next release.

**Closed** 2020-08-09 05:57 UTC
Labels: bug, reproduced

**Comment by bglasgo** [comment] 2020-08-11 04:45
beautiful, great job!
