### ISSUE TITLE
Show community feature

### ISSUE THREAD

**Issue by vhrtanek** [visjs/vis-network#378] opened 2020-01-24 08:36 UTC
Hi guys, 

first of all good job with vis-network package. I was wondering if you have ever considered adding feature for community visualization? So far we have been coloring nodes based on pre-computed community, but it would be helpful, if we can highlight underlying area of the community. I have in mind something as is in "igraph" library for R.

![82081284_2587267238221155_6770212959353307136_n](https://user-images.githubusercontent.com/3843071/73055260-aef72f00-3e8c-11ea-9868-484c0795d50b.png)

Would it be possible to add such a feature?

**Comment by Thomaash** [comment] 2020-01-24 12:58
Hi @vhrtanek,

could you have a look and compare this with the proposed districts from #203, please? It looks quite similar though I'm not sure it's the same.

**Comment by vhrtanek** [comment] 2020-01-27 08:04
Hi @Thomaash,

Indeed it's. I think the approach proposed by Muntaner will work for us and we will be able to replicate picture above in Vis.js. 

Thanks a lot

**Comment by Thomaash** [comment] 2020-01-27 18:29
Duplicate of #203.

**Closed by Thomaash** 2020-01-27 18:29 UTC
Labels: duplicate, enhancement
